### ISSUE TITLE
Error when building "bindist" app for Diligent PIC32 Wifire

### ISSUE THREAD

**Issue by danpetry** [riot-appstore/rapstore-django#27]
After hitting "Download binary file", the button just goes purple and no file is downloaded. Error output below:

```
web_1       | [26/Apr/2018 13:26:22] "GET /api/app/3/ HTTP/1.1" 200 704
web_1       | [26/Apr/2018 13:26:24] "GET /api/app/3/ HTTP/1.1" 200 704
builder_1   | [26/Apr/2018 13:26:24] "POST /supported_boards/ HTTP/1.1" 200 1746
web_1       | [26/Apr/2018 13:26:24] "GET /api/app/3/supported_boards/ HTTP/1.1" 200 16557
builder_1   | Internal Server Error: /build/
builder_1   | Traceback (most recent call last):
builder_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
builder_1   |     response = get_response(request)
builder_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
builder_1   |     response = self.process_exception_by_middleware(e, request)
builder_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
builder_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
builder_1   |   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
builder_1   |     return view_func(*args, **kwargs)
builder_1   |   File "/code/api/views.py", line 88, in build
builder_1   |     with open(dest+'/app.elf', 'rb') as file:
builder_1   | IOError: [Errno 2] No such file or directory: '/tmp/tmpaQollh/app.elf'
builder_1   | [26/Apr/2018 13:26:27] "POST /build/ HTTP/1.1" 500 63121
web_1       | [26/Apr/2018 13:26:27] "GET /api/app/3/build/?board=57 HTTP/1.1" 200 5
```

**Comment by jia200x** [comment]
I think it's because the MIPS toolchain is not installed. We should use the RIOT-docker script to install this.

Thanks for reporting
